project:
  type: website
  render:
    - "**/*.qmd"
    - "!archive/"
    
website:
  site-url: "https://michelleg06.github.io/dude_website2"
  title: "Dutch Development Economics Network"
  description: "A website to to facilitate knowledge exchange and connections among development economists based in the Netherlands."
  open-graph:
    image: images/dude_banner.svg
    image-alt: "Explaining an economic game to farmers in Masaka, Uganda."
  twitter-card:
    image: images/dude_banner.svg
    image-alt: "Explaining an economic game to farmers in Masaka, Uganda."
    card-style: summary_large_image
  favicon: images/favicon.ico
  navbar:
    background: "#472605"
    foreground: "#FFFFFF"
    title: ""
    search: true
    logo: images/logos/dude_logo_m2.svg
    right:
      - text: "Posts"
        icon: journal-text
        href: posts/blog/index.qmd
      - text: "Members"
        icon: people-fill
        menu:
        - href: members/universities/index.qmd
          text: "Affiliated Universities"
        - href: members/members/index.qmd
          text: "Members"
      - text: "Events"
        icon: calendar-event
        href: events/index.qmd
      - text: "Contact"
        icon: envelope
        href: "#contact"
      - href: https://github.com/michelleg06/dude_website2
        icon: github
  announcement:
    icon: info-circle
    dismissable: true
    content: "This site is under construction!"
    type: warning
    position: below-navbar

format:
  html:
    fontsize: 1.15rem
    include-after-body: _footer.html
    monofont: Fira Code
    highlight-style: arrow
    theme: custom_theme.scss
    css: theme.css
    toc: true
    code-overflow: scroll
    linkcolor: "#B8573E"
