# ✅ GitHub Actions workflow to render and deploy a Quarto site to GitHub Pages
name: Quarto Render and Deploy

on:
  # Runs on pushes to main branch
  push:
    branches: ["main"]

  # Allows manual trigger from Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4

      - name: ✅ Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: ✅ (Optional) Install Pandoc (if needed for rendering)
        uses: r-lib/actions/setup-pandoc@v2

      # Optional: add setup for R/Python if needed
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      - name: ✅ Render Quarto site
        run: quarto render

      - name: ✅ Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: ✅ Upload site artifact (_site/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: ✅ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
